#!/usr/bin/env python3
"""
Quick cookie extractor - paste cookies directly from DevTools table.
This version handles the paste better by reading from stdin.
"""

import json
import sys

def main():
    print("=" * 60)
    print("Quick Cookie Extractor")
    print("=" * 60)
    print("\nPaste your cookies from DevTools (tab-separated table format)")
    print("Press Ctrl+D when done (or Ctrl+Z on Windows)")
    print("-" * 60)
    
    # Read all input at once
    try:
        lines = sys.stdin.readlines()
    except KeyboardInterrupt:
        print("\n\nCancelled.")
        return
    
    if not lines:
        print("\n❌ No input received.")
        return
    
    cookies = []
    
    # Process each line
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        
        # Check if it's tab-separated (DevTools table format)
        if '\t' in line:
            parts = line.split('\t')
            if len(parts) >= 2:
                name = parts[0].strip()
                value = parts[1].strip()
                
                # Skip header row
                if name.lower() in ['name', 'cookie name', '']:
                    continue
                
                if name and value:
                    # Extract domain if available (usually column 2 or 3)
                    domain = '.justice.gov'
                    for i in range(2, min(5, len(parts))):
                        domain_part = parts[i].strip()
                        if domain_part and (domain_part.startswith('.') or 'justice.gov' in domain_part):
                            domain = domain_part if domain_part.startswith('.') else '.' + domain_part
                            break
                    
                    cookies.append({
                        'name': name,
                        'value': value,
                        'domain': domain,
                        'path': '/'
                    })
        # Check if it's name=value format
        elif '=' in line:
            parts = line.split('=', 1)
            name = parts[0].strip()
            value = parts[1].strip()
            if name and value:
                cookies.append({
                    'name': name,
                    'value': value,
                    'domain': '.justice.gov',
                    'path': '/'
                })
    
    if not cookies:
        print("\n❌ No cookies found. Make sure you copied the cookie table correctly.")
        return
    
    # Save cookies
    # JSON format
    with open('cookies.json', 'w') as f:
        json.dump(cookies, f, indent=2)
    
    # Netscape format
    with open('cookies.txt', 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# http://curl.haxx.se/rfc/cookie_spec.html\n")
        f.write("# This file was generated by quick cookie extractor\n")
        
        for cookie in cookies:
            domain = cookie.get('domain', '.justice.gov')
            if not domain.startswith('.'):
                domain = '.' + domain.lstrip('.')
            
            f.write(f"{domain}\tTRUE\t/\tFALSE\t0\t{cookie['name']}\t{cookie['value']}\n")
    
    print(f"\n✓ Saved {len(cookies)} cookies to:")
    print("  - cookies.json")
    print("  - cookies.txt")
    print("\nCookie names:")
    for cookie in cookies[:15]:
        print(f"  - {cookie['name']}")
    if len(cookies) > 15:
        print(f"  ... and {len(cookies) - 15} more")

if __name__ == "__main__":
    main()
